import {
  BookAIcon,
    Code,
    FileImage,
    ImageDownIcon,
    Mail,
    // MailCheckIcon,
    MessageSquare,
    // Music,
    PenIcon,
    SpeechIcon,
    // VideoIcon,
  } from "lucide-react";

export const tools = [
    {
      label: "Chat with Rachel",
      icon: MessageSquare,
      href: "/conversation",
      color: "text-violet-500",
      bgColor: "bg-violet-500/10",
    },
    {
      label: "Easy Learning",
      icon: BookAIcon,
      href: "/easylearning",
      color: "text-orange-500",
      bgColor: "bg-orange-500/10",
    },
    // {
    //   label: "Music Generation",
    //   icon: Music,
    //   href: "/music",
    //   color: "text-emerald-500",
    //   bgColor: "bg-emerald-500/10",
    // },
    {
      label: "Image Generation",
      icon: FileImage,
      color: "text-pink-700",
      bgColor: "bg-pink-700/10",
      href: "/image",
    },
    // {
    //   label: "Video Generation",
    //   icon: VideoIcon,
    //   color: "text-orange-700",
    //   bgColor: "bg-orange-700/10",
    //   href: "/video",
    // },
    {
      label: "Code Generation",
      icon: Code,
      color: "text-green-700",
      bgColor: "bg-green-700/10",
      href: "/code",
    },
    {
      label: "Social Captions",
      icon: PenIcon,
      href: "/socialmediaCaptions",
      bgColor: "bg-pink-700/10",
      color: "text-pink-400",
    },
    {
      label: "Email Writer",
      icon: Mail,
      href: "/email",
      bgColor: "bg-cyan-700/10",
      color: "text-cyan-400",
    },
    {
      label: "Text to Speech",
      icon: SpeechIcon,
      href: "/textToSpeech",
      color: "text-green-300",
      bgColor: "bg-green-500/10",
    },
    {
      label: "Talk to Image",
      icon: ImageDownIcon,
      href: "/chatWithImage",
      color: "text-cyan-700",
      bgColor: "bg-cyan-600/10",
    },
    // {
    //     label: "Cover Letter ",
    //     icon: MailCheckIcon,
    //     href: "/coverletter",
    //     color: "text-gray-500",
    //     bgColor: "bg-gray-700/10",
    //   },
  ];